# all the constraints definitions to run the program (time in minutes)
LOCOMOTION_CAPACITY = 50
SERVICE_START = 6 * 60
SERVICE_END = 24 * 60
MIN_TIME_BETWEEN_STOPS = 3
MAX_TIME_BETWEEN_STOPS = 10
NUM_LOCOMOTIONS = 100
MIN_DEMANDS = 1800
MAX_DEMANDS = 2100
DIRECTION_REPARTITION = (50, 50)
PEAK_TIME_INTERVALS = [(SERVICE_START, 10 * 60), (10 * 60, 16 * 60), (16 * 60, 20 * 60), (20 * 60, SERVICE_END)]
MAX_LOCOMOTION_SLOT_VARIATION = 10
DEMAND_INSTANCE_HEADERS = ['Arrival time', 'Boarding stop', 'Stops to go', 'Direction']
PLAN_INSTANCE_HEADERS = ['Direction', 'Departure Time', 'Duration (minutes)']
UP_TERMINUS = "Gare TGV"
DOWN_TERMINUS = "VALDOIE "